name: Run Composer Update

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run Composer Update
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd skyblock.fflnvb.de
          /opt/plesk/php/8.3/bin/php /usr/lib/plesk-9.0/composer.phar update --optimize-autoloader --no-dev



