name: Deploy Live

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # export NVM_DIR=~/.nvm
          # source ~/.nvm/nvm.sh
          rm -r -f skyblock.fflnvb.de
          git clone https://oauth2:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jpfauatwork/skyblock.fflnvb.de.git
          cp .skyblock.env skyblock.fflnvb.de/.env
          cd skyblock.fflnvb.de
          /opt/plesk/php/8.3/bin/php /usr/lib/plesk-9.0/composer.phar install --optimize-autoloader --no-dev
          # /opt/plesk/php/8.3/bin/php artisan migrate:fresh --seed --force
          /opt/plesk/php/8.3/bin/php artisan key:generate
          /opt/plesk/php/8.3/bin/php artisan config:cache
          /opt/plesk/php/8.3/bin/php artisan route:cache
          /opt/plesk/php/8.3/bin/php artisan view:cache
          # npm install
          # npm run build


